module.exports = [{bitcoin_id: 1,
    bitcoin_name: "Bitcoin",
    bitcoin_price: "1220.58",
bitcoin_circulating_supply: "19.5M",
bitcoin_cryptocurrency_popularity: 1,
bitcoin_marketCap: "$325.5B",
bitcoin_price_change_1D: "0.08%",
bitcoin_price_change_7D: "-1.67%"},
 {bitcoin_id: 2,
    bitcoin_name: "Bitcoin",
    bitcoin_price: "12000.21",
    bitcoin_circulating_supply: "21.9M",
    bitcoin_cryptocurrency_popularity: 1,
    bitcoin_marketCap: "$415.2B",
    bitcoin_price_change_1D: "2.24%",
    bitcoin_price_change_7D: "-16.787%"}]