module.exports = [
    {ethereum_id: 1,
        ethereum_name: "Ethereum",
ethereum_price: 1005.98,
ethereum_circulating_supply: "124.5M",
ethereum_cryptocurrency_popularity: 2,
ethereum_marketCap: "$110.5B",
ethereum_price_change_1D: "2.08%",
ethereum_price_change_7D: "7.67%"},
 {ethereum_id: 2,
    ethereum_name: "Ethereum",
    ethereum_price: 954.21,
    ethereum_circulating_supply: "109.9M",
    ethereum_cryptocurrency_popularity: 3,
    ethereum_marketCap: "$150.8B",
    ethereum_price_change_1D: "-0.24%",
    ethereum_price_change_7D: "-3.67%"}]